apiVersion: apps/v1
kind: Deployment
metadata:
  name: nick-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nick-web-app
  template:
    metadata:
      labels:
        app: nick-web-app
    spec:
      containers:
      - name: nick-web-app-container
        image: 738013621832.dkr.ecr.us-east-1.amazonaws.com/nick-ecr:v0.1.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
          protocol: TCP
